id: opecha:P007921
initial_creation_type: ocr
source_metadata:
  id: bdr:W29046
  title: བརྒལ་ལན་ཀུན་ཁྱབ་འབྲུག་སྒྲ་༔་གདོང་ཐོག་སྤྲུལ་སྐུ་ལ་གདམས་པ་བརྒལ་ལན་ཀུན་ཁྱབ་སྙན་པའི་འབྲུག་སྒྲ
  volume: ''
  author: ''
