id: P007921
initial_creation_type: ocr
source_metadata:
  id: bdr:W29046
  title: བརྒལ་ལན་ཀུན་ཁྱབ་འབྲུག་སྒྲ་༔་གདོང་ཐོག་སྤྲུལ་སྐུ་ལ་གདམས་པ་བརྒལ་ལན་ཀུན་ཁྱབ་སྙན་པའི་འབྲུག་སྒྲ
  author: ''
  volumes:
    21063adbfe024786811c7dab86297bd8:
      image_group_id: I00EGS1017298
      title: ''
      volume_number: 1
      total_pages: 242
ebook_metadata:
  title: བརྒལ་ལན་ཀུན་ཁྱབ་འབྲུག་སྒྲ་༔་གདོང་ཐོག་སྤྲུལ་སྐུ་ལ་གདམས་པ་བརྒལ་ལན་ཀུན་ཁྱབ་སྙན་པའི་འབྲུག་སྒྲ
  author: ''
  sku: P007921
  cover: cover.jpg
  layers:
  - pagination
