id: I586C366F
legacy_id: P007921
ocr_import_info:
  bdrc_scan_id: W29046
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T16:50:48'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T09:46:06.851533+00:00'
last_modified: 2022-09-02 17:46:26.203339
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29046
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29046
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བརྒལ་ལན་ཀུན་ཁྱབ་འབྲུག་སྒྲ་༔་གདོང་ཐོག་སྤྲུལ་སྐུ་ལ་གདམས་པ་བརྒལ་ལན་ཀུན་ཁྱབ་སྙན་པའི་འབྲུག་སྒྲ།
  author: ཡོན་ཏན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7477981419875944
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I00EGS1017298:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017298
      total_pages: 242
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1017298.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7477981419875944
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
