id: I586C366F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:52:21+00:00'
last_modified: '2022-06-09T07:31:38.266012+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29046
  title: བརྒལ་ལན་ཀུན་ཁྱབ་འབྲུག་སྒྲ་༔་གདོང་ཐོག་སྤྲུལ་སྐུ་ལ་གདམས་པ་བརྒལ་ལན་ཀུན་ཁྱབ་སྙན་པའི་འབྲུག་སྒྲ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DB28:
      image_group_id: I00EGS1017298
      title: 'Volume 1 of brgal lan kun khyab ''brug sgra : gdong thog sprul sku la
        gdams pa brgal lan kun khyab snyan pa''i ''brug sgra'
      total_pages: 242
      order: 1
      base_file: DB28.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
